formula_parser:
  confidence_threshold: 0.7
  enable_latex_validation: true
  engine: pp_formulanet
  max_formula_height: 500
  max_formula_width: 1000
  model_size: L

ocr_processor:
  confidence_threshold: 0.8
  det_db_box_thresh: 0.6
  det_db_thresh: 0.3
  engine: paddleocr
  language: ch
  use_gpu: true
  ocr_version: PP-OCRv5

layout_analyzer:
  # 模型配置
  model_path: "doclayout.pt"        # DocLayout模型权重文件路径
  model_type: "doclayout"           # 模型类型
  
  # 推理配置
  confidence_threshold: 0.4         # 置信度阈值
  iou_threshold: 0.40              # IoU阈值用于NMS
  use_gpu: true                  # 是否使用GPU
  batch_size: 4                    # 批处理大小
  max_det: 300                     # 最大检测数量
  input_size: 1024                 # 输入图像尺寸
  
  # 后处理配置
  min_region_area: 100.0            # 最小区域面积
  
  # 可视化配置
  visualization_enabled: true      # 启用可视化
  show_confidence: true           # 显示置信度
  show_class_names: true          # 显示类别名称
  bbox_thickness: 2               # 边界框粗细
  
md_generator:
  formula_format: latex
  image_format: png
  include_metadata: true
  include_page_breaks: true
  line_break_style: double
  max_line_length: 80
  preserve_formatting: false
  table_format: markdown
  title_level_thresholds:
    level_1: 16
    level_2: 14
    level_3: 12
    level_4: 10
    level_5: 8
pdf_converter:
  dpi: 300
  format: PNG
  poppler_path: null
  quality: 95
  single_thread: true
  use_cairo: true
reading_order:
  algorithm: layoutreader
  batch_size: 2
  column_detection: true
  confidence_threshold: 0.4
  layout_reader_model_path: hantian/layoutreader
  max_sequence_length: 1024
table_parser:
  confidence_threshold: 0.7
  merge_threshold: 0.2
  method: PPStructureV3
  min_table_size: 2
  use_gpu: true
